<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'theseer\\journald\\journalentry' => '/JournalEntry.php',
                'theseer\\journald\\journalentryexception' => '/JournalEntryException.php',
                'theseer\\journald\\journalwriter' => '/JournalWriter.php',
                'theseer\\journald\\socketpath' => '/SocketPath.php',
                'theseer\\journald\\socketpathexception' => '/SocketPathException.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
