<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'theseer\\journalwriter\\journalwriter'         => '/JournalWriter.php',
                'theseer\\journalwriter\\journalentry'          => '/JournalEntry.php',
                'theseer\\journalwriter\\journalentryexception' => '/JournalEntryException.php',
                'theseer\\journalwriter\\socketpath'            => '/SocketPath.php',
                'theseer\\journalwriter\\socketpathexception'   => '/SocketPathException.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
